spring.application.name= FromTheAshes

spring.datasource.url=${MY_DATASOURCE_URL}
spring.datasource.username=${MY_DB_USERNAME}
spring.datasource.password=${MY_DB_PASSWORD}

spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation= true
spring.jpa.properties.hibernate.dialect= org.hibernate.dialect.PostgreSQLDialect

# Hibernate ddl auto (create, create-drop, validate, update)
spring.jpa.hibernate.ddl-auto= update

server.port= 8081

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB